iumecregister/urls.py
from django.contrib import admin
from django.conf.urls import url
from assist_control.views import *
from django.contrib.auth.views import LoginView
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home, name='index'),
    url(r'^login/$', LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^assist/register/$', register_assistance, name='register_assistance'),
    url(r'^services/list/$', services_list, name='services_list'),
    url(r'^services/(?P<service_pk>[0-9]+)/assistants/$', service_assistants, name='service_assistants'),
    url(r'^services/assistants/(?P<assistant_service_pk>[0-9]+)/complete/$', complete_assistant, name='complete_assistant'),
    url(r'^services/(?P<service_pk>[0-9]+)/assistants/delete$', remove_non_attendees, name='remove_non_attendees'),
    url(r'^assistants/(?P<assistant_service_pk>[0-9]+)/edit/$', edit_assistant, name='edit_assistant'),
    url(r'^assistants/(?P<assistant_service_pk>[0-9]+)/remove/$', remove_non_attendee, name='remove_non_attendee'),
    url(r'^assist/servant/register/$', register_servant, name='register_servant'),
]

assist_control/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth.models import User
from .models import Assistant
from django.forms import ModelForm

class RegisterForm(forms.Form):
    username = forms.CharField(required=True)
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    phone = forms.CharField(required=False)
    date_id = forms.IntegerField(required=True)
    age = forms.IntegerField(required=True)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'phone', 'age')


class CompleteAssistan(ModelForm):
    SYMPTOMS = (
        ('f', 'Fiebre'),
        ('t', 'Tos'),
        ('c', 'Cefalea'),
        ('dg', 'Dolor de Garganta'),
        ('mg', 'Malestar General'),
        ('dr', 'Dificultad Respiratoria'),
        ('a', 'Adinamia'),
        ('sn', 'Secreciones Nasales'),
        ('d', 'Diarrea'),
    )

    id = forms.CharField(required=True, widget=forms.TextInput(attrs={'class':'form-control', 'readonly':'readonly'}))
    name = forms.CharField(required=True, widget=forms.TextInput(attrs={'class':'form-control', 'readonly':'readonly'}))
    last_name = forms.CharField(required=True, widget=forms.TextInput(attrs={'class':'form-control', 'readonly':'readonly'}))
    age = forms.IntegerField(required=False, widget=forms.NumberInput(attrs={'class':'form-control', 'readonly':'readonly'}))
    phone = forms.CharField(required=False, widget=forms.TextInput(attrs={'class':'form-control'}))
    address = forms.CharField(required=False, widget=forms.TextInput(attrs={'class':'form-control'}))
    temperature = forms.DecimalField(required=True, widget=forms.NumberInput(attrs={'class':'form-control'}))
    symptoms = forms.MultipleChoiceField(
        required=False,
        widget=forms.CheckboxSelectMultiple(attrs={'class':'list-group list-group-flush'}),
        choices=SYMPTOMS,
    )
    close_person = forms.BooleanField(required=False)
    washed = forms.BooleanField(required=False)
    agree = forms.BooleanField(required=False)
    was_returned = forms.BooleanField(required=False)

    def __init__(self, *args, **kwargs):
        super(CompleteAssistan, self).__init__(*args, **kwargs)
        self.fields['id'].label = "Número de Identificación"
        self.fields['name'].label = "Nombre(s)"
        self.fields['last_name'].label = "Apellidos"
        self.fields['age'].label = "Edad"
        self.fields['phone'].label = "Teléfono"
        self.fields['address'].label = "Dirección"
        self.fields['temperature'].label = "Temperatura"
        self.fields['symptoms'].label = "¿Ha presentado alguno de estos síntomas en las últimas 24 horas?"
        self.fields['close_person'].label = "¿Ha estado en contacto con alguien que presente los anteriores sintomas en las últimas 24 horas?"
        self.fields['washed'].label = "¿Realizó el lavado o desinfección de las manos antes de ingresar a las instalaciones?"
        self.fields['agree'].label = "¿Está de acuerdo en cumplir a cabalidad con todas las recomendaciones y los procedimientos que la iglesia ha adoptado para la preservación de su salud?"
        self.fields['was_returned'].label = "¿Se le niega el ingreso a las instalaciones y se recomienda que regrese a casa?"

    class Meta:
        model = Assistant
        fields = ('id', 'name', 'last_name', 'age', 'phone', 'address')


class EditAssistan(ModelForm):
    id = forms.CharField(required=True, widget=forms.TextInput(attrs={'class':'form-control', 'readonly':'readonly'}))
    name = forms.CharField(required=True, widget=forms.TextInput(attrs={'class':'form-control'}))
    last_name = forms.CharField(required=True, widget=forms.TextInput(attrs={'class':'form-control'}))
    age = forms.IntegerField(required=True, widget=forms.NumberInput(attrs={'class':'form-control'}))
    phone = forms.CharField(required=False, widget=forms.TextInput(attrs={'class':'form-control'}))
    address = forms.CharField(required=False, widget=forms.TextInput(attrs={'class':'form-control'}))

    def __init__(self, *args, **kwargs):
        super(EditAssistan, self).__init__(*args, **kwargs)
        self.fields['id'].label = "Número de Identificación"
        self.fields['name'].label = "Nombre(s)"
        self.fields['last_name'].label = "Apellidos"
        self.fields['phone'].label = "Teléfono"
        self.fields['age'].label = "Edad"
        self.fields['address'].label = "Dirección"

    class Meta:
        model = Assistant
        fields = ('id', 'name', 'last_name', 'age', 'phone', 'address')


class RegisterServant(forms.Form):
    SYMPTOMS = (
        ('f', 'Fiebre'),
        ('t', 'Tos'),
        ('c', 'Cefalea'),
        ('dg', 'Dolor de Garganta'),
        ('mg', 'Malestar General'),
        ('dr', 'Dificultad Respiratoria'),
        ('a', 'Adinamia'),
        ('sn', 'Secreciones Nasales'),
        ('d', 'Diarrea'),
    )

    id = forms.CharField(required=True, widget=forms.TextInput(attrs={'class':'form-control'}))
    name = forms.CharField(required=True, widget=forms.TextInput(attrs={'class':'form-control'}))
    last_name = forms.CharField(required=True, widget=forms.TextInput(attrs={'class':'form-control'}))
    age = forms.IntegerField(required=False, widget=forms.NumberInput(attrs={'class':'form-control'}))
    phone = forms.CharField(required=False, widget=forms.TextInput(attrs={'class':'form-control'}))
    address = forms.CharField(required=False, widget=forms.TextInput(attrs={'class':'form-control'}))
    temperature = forms.DecimalField(required=True, widget=forms.NumberInput(attrs={'class':'form-control'}))
    symptoms = forms.MultipleChoiceField(
        required=False,
        widget=forms.CheckboxSelectMultiple(attrs={'class':'list-group list-group-flush'}),
        choices=SYMPTOMS,
    )
    close_person = forms.BooleanField(required=False)
    washed = forms.BooleanField(required=False)
    agree = forms.BooleanField(required=False)
    dates = forms.MultipleChoiceField(
        required=False,
        widget=forms.CheckboxSelectMultiple(attrs={'class':'list-group list-group-flush'}),
        choices=(),
    )

    def __init__(self, *args, **kwargs):
        choices = kwargs.pop('dates_tuples')
        super(RegisterServant, self).__init__(*args, **kwargs)
        self.fields['id'].label = "Número de Identificación"
        self.fields['name'].label = "Nombre(s)"
        self.fields['last_name'].label = "Apellidos"
        self.fields['age'].label = "Edad"
        self.fields['phone'].label = "Teléfono"
        self.fields['address'].label = "Dirección"
        self.fields['temperature'].label = "Temperatura"
        self.fields['symptoms'].label = "¿Ha presentado alguno de estos síntomas en las últimas 24 horas?"
        self.fields['close_person'].label = "¿Ha estado en contacto con alguien que presente los anteriores sintomas en las últimas 24 horas?"
        self.fields['washed'].label = "¿Realizó el lavado o desinfección de las manos antes de ingresar a las instalaciones?"
        self.fields['agree'].label = "¿Está de acuerdo en cumplir a cabalidad con todas las recomendaciones y los procedimientos que la iglesia ha adoptado para la preservación de su salud?"
        self.fields["dates"].choices = choices

    class Meta:
        model = Assistant
        fields = ('id', 'name', 'last_name', 'age', 'phone', 'address')

templates/register/register.html
{% extends 'index.html' %} {% load dates %} {% load static %} {% block content %}
  <div class="wrapper wrapper--w960" id="formRegister">
    <div class="card card-2">
      <div class="card-heading"></div>
        <div class="card-body">
            <div class="row" style="justify-content: flex-end;font-style:italic;">
              <a href="{% url 'services_list' %}">Administrar</a>
            </div>
            <h2 class="title">REGISTRO (IUMEC BUGA)</h2>
            {% if message and not success %}
              <div class="alert alert-danger" role="alert">
                  {{ message }}
              </div>
            {% endif %}
            {% if message and success %}
              <div class="alert alert-success" role="alert">
                  {{ message }}
              </div>
            {% endif %}
            <form method="POST" id="registerForm">
              {% csrf_token %}
              <div class="input-group">
                  <input class="input--style-2" type="number" placeholder="Número de Identificación" name="username" required>
              </div>
              <div class="row">
                <div class="col-12 col-md-6">
                  <div class="input-group">
                      <input class="input--style-2" type="text" placeholder="Nombre(s)" name="first_name" required>
                  </div>
                </div>
                <div class="col-12 col-md-6">
                  <div class="input-group">
                      <input class="input--style-2" type="text" placeholder="Apellidos" name="last_name" required>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-12 col-md-6">
                  <div class="input-group">
                      <input class="input--style-2" type="number" placeholder="Edad" id="age" name="age" required min="14">
                  </div>
                </div>
                <div class="col-12 col-md-6">
                  <div class="input-group" style="margin-bottom: 0px">
                      <input class="input--style-2" type="tel" placeholder="Número Celular" id="phone" name="phone" pattern="[0-9]{3}[0-9]{3}[0-9]{4}" maxlength="12" title="Por favor ingrese un número de celular válido Ejemplo: 3123456789">
                  </div>
                  <label style="margin-bottom: 25px;font-style:italic;color:#666;font-size: 13px;"><b>Nota:</b> En caso de no tener, dejar este campo vacío.</label>
                </div>
              </div>
              {% if not dates %}
                <p style="font-weight: bold;font-size: 15px;font-style: italic;margin-top: 15px;">Muy pronto estaremos publicando nuestros horarios para que te inscribas.</p>
              {% else %}
                <h4 style="font-weight:bold;margin-bottom:8px;">Fechas Disponibles <span style="font-size:13px;font-weight:100;font-style:italic;">(Seleccione una fecha presionando sobre el círculo)</span></h4>
                <div class="row row-space">
                  <div class="col-12">
                    {% for date in dates %}
                      <div style="margin-bottom:5px;">
                        <input style="width:auto;" type="radio" id="male" name="date_id" value="{{ date.id }}" required>
                        <label style="text-transform: capitalize;">{{ date.date | dates }}</label>
                      </div>
                    {% endfor %}
                  </div>
                </div>
              {% endif %}
              <div style="padding-top: 20px;">
                  <button class="btn btn--radius btn--green" {% if not dates %} disabled {% endif %} type="submit">Enviar</button>
              </div>
              <label style="font-style:italic;color:#666;font-size: 13px;margin-top: 11px;">
                <b>Notas:</b>
                <li>Sólo es posible registrarse a un servicio a la vez.</li>
                <li>Se recomienda estar 10 minutos antes en el sitio para evitar aglomeraciones.</li>
                <li>Se recomienda que si padece de alguna <b>Enfermedad de Base</b> evite asistir a las reuniones.</li>
              </label>
            </form>
        </div>
    </div>
  </div>
{% endblock %}

templates/register/servant-register.html
{% extends 'index.html' %} {% load dates %} {% load static %} {% block content %}
  <div class="wrapper wrapper--w960" id="formRegister">
    <div class="card card-2">
      <div class="card-heading"></div>
        <div class="card-body">
            <div class="row" style="justify-content: flex-end;font-style:italic;">
              <a href="{% url 'services_list' %}">Administrar</a>
            </div>
            <h2 class="title">REGISTRO (IUMEC BUGA)</h2>
            {% if message and not success %}
              <div class="alert alert-danger" role="alert">
                  {{ message }}
              </div>
            {% endif %}
            {% if message and success %}
              <div class="alert alert-success" role="alert">
                  {{ message }}
              </div>
            {% endif %}
            <form method="POST" id="registerServantForm">
              {% csrf_token %}
              <div class="input-group">
                  <input class="input--style-2" type="text" placeholder="Número de Identificación" name="id" required>
              </div>
              <div class="row">
                <div class="col-12 col-md-6">
                  <div class="input-group">
                      <input class="input--style-2" type="text" placeholder="Nombre(s)" name="name" required>
                  </div>
                </div>
                <div class="col-12 col-md-6">
                  <div class="input-group">
                      <input class="input--style-2" type="text" placeholder="Apellidos" name="last_name" required>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-12 col-md-6">
                  <div class="input-group">
                      <input class="input--style-2" type="number" placeholder="Edad" id="age" name="age" required>
                  </div>
                </div>
                <div class="col-12 col-md-6">
                  <div class="input-group">
                      <input class="input--style-2" type="tel" placeholder="Número Celular" id="phone" name="phone" pattern="[0-9]{3}[0-9]{3}[0-9]{4}" maxlength="12" title="Por favor ingrese un número de celular válido Ejemplo: 3123456789">
                  </div>
                  <label style="margin-bottom: 25px;font-style:italic;color:#666;font-size: 13px;"><b>Nota:</b> En caso de no tener, dejar este campo vacío.</label>
                </div>
              </div>
              <div class="row">
                <div class="col-12">
                  <div class="input-group">
                      <input class="input--style-2" type="text" placeholder="Dirección" id="address" name="address">
                  </div>
                </div>
              </div>
              {% if not dates %}
                <p style="font-weight: bold;font-size: 15px;font-style: italic;margin-top: 15px;">Muy pronto estaremos publicando nuestros horarios para que te inscribas.</p>
              {% else %}
                <h4 style="font-weight:bold;margin-bottom:8px;">Fechas Disponibles <span style="font-size:13px;font-weight:100;font-style:italic;">(Seleccione los servicios en los cuales estará)</span></h4>
                <div class="row row-space">
                  <div class="col-12">
                    {% for date in form.dates %}
                      <div style="margin-bottom:5px;">
                        <div class="allign-dates">{{ date }}</div>
                      </div>
                    {% endfor %}
                  </div>
                </div>
              {% endif %}
              <div class="row" style="margin-top:15px;">
                <div class="col-12">
                  <div class="input-group">
                      <input class="input--style-2" type="number" placeholder="Temperatura" id="temperature" name="temperature" required>
                  </div>
                </div>
              </div>
              <div class="form-group">
                <label style="font-weight:bold;font-style:italic;">¿Ha presentado alguno de estos síntomas en las últimas 24 horas?</label>
                <ul id="id_symptoms" class="list-group list-group-flush">
                  <li>
                    <label for="id_symptoms_0"><input type="checkbox" name="symptoms" value="f" class="list-group list-group-flush" id="id_symptoms_0"> Fiebre</label>
                  </li>
                  <li>
                    <label for="id_symptoms_1"><input type="checkbox" name="symptoms" value="t" class="list-group list-group-flush" id="id_symptoms_1">Tos</label>
                  </li>
                  <li>
                    <label for="id_symptoms_2"><input type="checkbox" name="symptoms" value="c" class="list-group list-group-flush" id="id_symptoms_2">Cefalea</label>
                  </li>
                  <li>
                    <label for="id_symptoms_3"><input type="checkbox" name="symptoms" value="dg" class="list-group list-group-flush" id="id_symptoms_3">Dolor de Garganta</label>
                  </li>
                  <li>
                    <label for="id_symptoms_4"><input type="checkbox" name="symptoms" value="mg" class="list-group list-group-flush" id="id_symptoms_4">Malestar General</label>
                  </li>
                  <li>
                    <label for="id_symptoms_5"><input type="checkbox" name="symptoms" value="dr" class="list-group list-group-flush" id="id_symptoms_5">Dificultad Respiratoria</label>
                  </li>
                  <li>
                    <label for="id_symptoms_6"><input type="checkbox" name="symptoms" value="a" class="list-group list-group-flush" id="id_symptoms_6">Adinamia</label>
                  </li>
                  <li>
                    <label for="id_symptoms_7"><input type="checkbox" name="symptoms" value="sn" class="list-group list-group-flush" id="id_symptoms_7">Secreciones Nasales</label>
                  </li>
                  <li>
                    <label for="id_symptoms_8"><input type="checkbox" name="symptoms" value="d" class="list-group list-group-flush" id="id_symptoms_8">Diarrea</label>
                  </li>
                </ul>
              </div>
              <div class="form-group">
                <label style="font-weight:bold;font-style:italic;" for="id_close_person">¿Ha estado en contacto con alguien que presente los anteriores sintomas en las últimas 24 horas?</label>
                <input type="checkbox" name="close_person" id="id_close_person">
              </div>
              <div class="form-group">
                <label style="font-weight:bold;font-style:italic;" for="id_washed">¿Realizó el lavado o desinfección de las manos antes de ingresar a las instalaciones?</label>
                <input type="checkbox" name="washed" id="id_washed">
              </div>
              <div class="form-group">
                <label style="font-weight:bold;font-style:italic;" for="id_agree">¿Está de acuerdo en cumplir a cabalidad con todas las recomendaciones y los procedimientos que la iglesia ha adoptado para la preservación de su salud?</label>
                <input type="checkbox" name="agree" id="id_agree">
              </div>
              <div style="padding-top: 20px;">
                  <button class="btn btn--radius btn--green" {% if not dates %} disabled {% endif %} type="submit">Enviar</button>
              </div>
            </form>
        </div>
    </div>
  </div>
{% endblock %}